config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  resources :services do
    resources :orders, only: %i[create new]
  end

  resources :orders, only: %i[index show] do
    resources :reviews
    member do
      patch :update_status
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  devise_for :users
  resources :users
  get 'gallery', to: 'static_pages#gallery'
  get 'profile', to: 'users#profile'
  get 'masters', to: 'masters#index'
  resources :masters, only: %i[index show]
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  validates :title, :performed, :description, :introduction, :image, presence: true
  validates :title, uniqueness: true

  has_one_attached :image, dependent: :destroy

  has_many :orders, dependent: :restrict_with_exception
  has_many :reviews, through: :orders, dependent: :restrict_with_exception
  belongs_to :category

  PERFOMED =  { 'on the coach' => "на кушетке с нанесением натурального арома-масла", 'on the mat' => "на мате в специальном хлопковом костюме" }

  enum performed: PERFOMED.keys.freeze
  enum duration: %i[1h 1.5h 2h]
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  def index
    @services = if params[:category_id].present?
                  Service.all.where('category_id = ?', params[:category_id]).order(rating: :desc)
                else
                  Service.all.order(rating: :desc)
                end
    @categories = Category.all
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/index.html.erb
<% provide(:title, "Услуги") %>
<div class="featurette-divider"></div>
<div class="text-center">
  <%= link_to 'Все', services_path, class: "btn btn-sm btn-dark m-1" %>
  <% @categories.each do |category| %>
    <%= link_to category.name.capitalize, services_path(category_id: category.id), class: "btn btn-sm btn-dark m-1" %>
  <% end %>
</div>
<% @services.each do |service| %>
  <div class="card text-dark bg-light p-1 mx-auto col-xl-6 col-lg-7 col-sm-9 my-5">
    <div class="card-body m-1 p-1">
      <div class="row">
        <div class="col-7">
          <span class="fw-bold fs-4"><%= service.title %></span>
        </div>
        <div class="col-5 text-end my-1"><%= number_to_currency(service.price) %>
          <div>
            <% service.fill_stars.times do %>
              <i class="bi bi-star-fill"></i>
            <% end %>
            <% service.blank_stars.times do %>
              <i class="bi bi-star"></i>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
      <div class="row">

        <div class="col-lg-6 col-md-12">
          <%= cl_image_tag(service.image.key,  style: "width: 400px; height: 250px;", class: "img-fluid rounded") %>
        </div>

        <div class="col-lg-6 col-md-12">
          <span class="fw-bold mx-auto" my-2>Выполнение: </span> <%= Service::PERFOMED.select {|key, value| key == service.performed }.values.first %><br>
          <p class="m-auto fw-bold my-2"><%= service.introduction %></p>

          <% if current_user.nil? %>
            <%= link_to 'Зарегистрироваться', new_user_registration_path, class: "btn btn-dark my-sm-1" %>
          <% elsif  current_user.client? %>
            <%= link_to 'Оформить', new_service_order_path(service), class: "btn btn-dark my-sm-1" %>
          <% end %>

          <%= link_to 'Подробнее', service_path(service), class: "btn btn-outline-dark mx-auto" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/services/new.html.erb
<% provide(:title, "New service") %>
<div class="container d-flex justify-content-center" style="min-width:720px!important">
  <div class="col-11 col-offset-2">
    <div class="progress mt-3" style="height: 30px;">
      <div class="progress-bar progress-bar-striped progress-bar-animated" style="font-weight:bold; font-size:15px;" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
    <div class="card mt-3">
      <div class="card-header font-weight-bold">My Bootstrap 5 multi-step-form</div>
      <div class="card-body p-4 step">
        <div class="radio-group row justify-content-between px-3 text-center" style="justify-content:center !important">
          <div class="col-auto me-sm-2 mx-1 card-block py-0 text-center radio">
            <div class="opt-icon"><i class="fas fa-user-plus" style="font-size: 80px; margin-left: 25px;"></i></div>
            <p><b>Add new user</b></p>
          </div>
          <div id="suser" class="selected col-auto ms-sm-2 mx-1 card-block py-0 text-center radio">
            <div class="opt-icon"><i class="fas fa-users" style="font-size: 80px;"></i></div>
            <p><b>Search existing user</b></p>
          </div>
        </div>
        <div class="searchfield text-center pb-1" style="font-size:12px">Search for example <b>Gary Hendren</b></div>
        <div class="searchfield input-group px-5">
          <span class="input-group-text" id="basic-addon1"><i class="fas fa-search text-white" aria-hidden="true"></i></span>
          <input id="txt-search" class="form-control" type="text" placeholder="Search" aria-label="Search">
        </div>
        <div id="filter-records" class="mx-5"></div>
      </div>
      <div id="userinfo" class="card-body p-4 step" style="display: none">
        <div class="text-center">
          <h5 class="card-title font-weight-bold pb-2">User information</h5>
        </div>

        <div class="form-group row">
          <div class="col-2"></div>
          <div class="col-4">
            <label for="fname">First Name<b style="color: #dc3545;">*</b></label>
            <input type="text" name="name" class="form-control" id="fname" required>
            <div class="invalid-feedback">This field is required</div>
          </div>
          <div class="col-4">
            <label for="lname">Last Name<b style="color: #dc3545;">*</b></label>
            <input type="text" class="form-control" id="lname" required>
            <div class="invalid-feedback">This field is required</div>
          </div>
        </div>
        <div class="form-group row pt-2">
          <label for="team" class="col-2 text-end control-label col-form-label">Team</label>
          <div class="col-8">
            <input type="text" class="form-control" id="team">
          </div>
        </div>
        <div class="form-group row pt-2">
          <label for="address" class="col-2 text-end control-label col-form-label">Address</label>
          <div class="col-8">
            <input type="text" class="form-control" id="address">
          </div>
        </div>
        <div class="form-group row pt-2">
          <label for="tel" class="col-2 text-end control-label col-form-label">Tel/Gsm</label>
          <div class="col-8">
            <input type="text" class="form-control" id="tel">
          </div>
        </div>
        <div class="text-center text-muted"><b style="color: #dc3545;">*</b> required fields</div>
      </div>
      <div class="card-body p-5 step" style="display: none">Step 3</div>
      <div class="card-body p-5 step" style="display: none">Step 4</div>
      <div class="card-body p-5 step" style="display: none">Step 5</div>
      <div class="card-footer">
        <button class="action back btn btn-sm btn-outline-warning" style="display: none">Back</button>
        <button class="action next btn btn-sm btn-outline-secondary float-end" disabled="">Next</button>
        <button class="action submit btn btn-sm btn-outline-success float-end" style="display: none">Submit</button>
      </div>
    </div>

  </div>
</div>

app/views/services/show.html.erb
<% provide(:title, "#{@service.title}") %>
<div class=" text-dark p-1 mx-auto col-xl-6 col-lg-7 col-sm-9 featurette-divider">
  <div class="my-1 p-1">
    <div class="row">
      <div class="col-8">
        <span class="fw-bold fs-4"><%= @service.title %></span>
        <br>
          <% @service.fill_stars.times do %>
            <i class="bi bi-star-fill"></i>
          <% end %>
          <% @service.blank_stars.times do %>
            <i class="bi bi-star"></i>
          <% end %>
        <br>
        <i>Всего отзывов: <%= @service.reviews.unblock.count %>
        </i>

      </div>
      <div class="col-4 text-end">
        <% if current_user.nil? %>
          <%= link_to 'Зарегистрироваться', new_user_registration_path, class: "btn btn-dark my-sm-1" %>
        <% elsif  current_user.client? %>
          <%= link_to 'Заказать', new_service_order_path(@service), class: "btn btn-dark my-sm-1" %>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="row my-3">

      <div class="col-lg-6 col-md-12">
        <%= cl_image_tag(@service.image.key, width: 400, height: 250, class: "img-fluid rounded") %>
      </div>

      <div class="col-lg-6 col-md-12">
        <span class="fw-bold mx-auto">Выполенение: </span><%= Service::PERFOMED.select {|key, value| key == @service.performed }.values.first %><br>
        <span class="fw-bold mx-auto">Цена: </span><%= number_to_currency(@service.price) %><br>
        <p class="my-3"><%= @service.introduction %></p>
      </div>
    </div>
    <hr>
    <p align="justify"><%= @service.description %></p>
  </div>
  <div id="reviews">
    <%= render @service.reviews.unblock %>
  </div>
</div>