config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  resources :services do
    resources :orders, only: %i[create new]
  end

  resources :orders, only: %i[index show] do
    resources :reviews
    member do
      patch :update_status
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  devise_for :users
  resources :users
  get 'gallery', to: 'static_pages#gallery'
  get 'profile', to: 'users#profile'
  get 'masters', to: 'masters#index'
  resources :masters, only: %i[index show]
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def gallery; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/gallery.html.erb
<% provide(:title, "Галерея") %>
<div class="row text-center px-5">
  <% Dir.glob('app/assets/images/gallery/*').map do |path| %>
    <div class="col-md-3 col-sm-6 my-2">
      <%= image_tag "gallery/#{ File.basename(path) }", size: "500x300", onclick:"openModal();currentSlide(1)", class: "hover-shadow img-fluid" %>
    </div>
  <% end %>
</div>

<div id="myModal" class="modal featurette-divider ">

  <div class="modal-content">
    <span class="close cursor text-dark" onclick="closeModal()">&times</span>

    <% Dir.glob('app/assets/images/gallery/*').map do |path| %>
      <div class="mySlides">
        <%= image_tag "gallery/#{ File.basename(path) }", width: "1200", class: "img-fluid" %>
      </div>
    <% end %>

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <div class="caption-container">
      <p id="caption"></p>
    </div>

  </div>
</div>
<%= javascript_include_tag 'gallery.js' %>
<%= stylesheet_link_tag "gallery", "data-turbo-track": "reload" %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Главная") %>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>

    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag "home/photo4.jpg", class: "img-fluid" %>
        <div class="container">
          <div class="carousel-caption">
            <h3>Время, потраченное на массаж, никогда не пропадает зря</h3>
            <%= link_to 'Зарегистрироваться', new_user_registration_path, class: "btn btn-lg btn-outline-light mt-1" %>
          </div>
        </div>
      </div>
      <div class="carousel-item">

        <%= image_tag "home/photo5.jpg", class: "img-fluid" %>
        <div class="container">
          <div class="carousel-caption">
            <h3>Отдохните, и ваша энергия восстановится.</h3>
            <%= link_to 'Услуги', services_path, class: "btn btn-lg btn-outline-light mt-1" %>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag ("home/photo6.jpg"), class: "img-fluid" %>
        <div class="container">
          <div class="carousel-caption">
            <h3>Открой свою душу. И свои глаза.</h3>
              <%= link_to 'Просмотреть галерею', gallery_path, class: "btn btn-lg btn-outline-light mt-1" %>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Назад</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Вперед</span>
    </button>
  </div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row" id="about">
      <div class="col-lg-4">
        <%= image_tag "home/photo9.jpg", class: "rounded-circle", size: "150x150" %>
        <h2>Hermann Hesse</h2>
        <p>Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <%= image_tag "home/photo8.jpg", class: "rounded-circle", size: "150x150" %>
        <h2>Mandy Hals</h2>
        <p>It’s not selfish to love yourself, take care of yourself, and to make your happiness a priority. It’s necessary.</p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <%= image_tag "home/photo7.jpg", class: "rounded-circle", size: "150x150" %>
        <h2>Paulo Coelho</h2>
        <p>It’s a good idea always to do something relaxing before making an important decision in your life.</p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->
  </div>