config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  resources :services do
    resources :orders, only: %i[create new]
  end

  resources :orders, only: %i[index show] do
    resources :reviews
    member do
      patch :update_status
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  devise_for :users
  resources :users
  get 'gallery', to: 'static_pages#gallery'
  get 'profile', to: 'users#profile'
  get 'masters', to: 'masters#index'
  resources :masters, only: %i[index show]
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :service
  belongs_to :user, class_name: 'User'
  belongs_to :master, class_name: 'User'
  has_one :review, dependent: :restrict_with_exception

  validates :startdate, presence: true

  STATUSES =  {:draft => "Черновик", :cancel => "Отменен", :confirm => "Подтвержден", :complete => "Завершен" }

  enum status: STATUSES.keys.freeze

  enum role: %i[client master]

  scope :status, ->(status) { where('status = ?', status) }
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = if params[:status].present?
                current_user.orders.status(Order::STATUSES.values.index(params[:status].to_sym))
              else
                current_user.orders.order(:startdate)
              end

    @masters = User.master
  end

  def update_status
    @order = Order.find(params[:id])
    @order.update(status: params[:status])
    redirect_to @order, notice: "Статус изменен на '#{@order.status}'"
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @service = Service.find(params[:service_id])
    @masters = User.master.order(rating: :desc)
    @master = params[:master_id]
    disable_date = Order.not_cancel.select(:startdate).where('master_id = ? and startdate > current_date', @master)
    @disable_date = []
    i = disable_date.size - 1
    while i >= 0
      @disable_date.push(disable_date[i].startdate.to_s)
      i -= 1
    end
  end

  def create
    @service = Service.find(params[:service_id])
    @order = @service.orders.create(order_params.merge(user_id: current_user.id, master_id: params[:master_id]))

    if @order.save
      flash[:success] = 'Order created successfully.'
      redirect_to @order
    else
      flash[:danger] = @order.errors.full_messages
      if params[:master_id].empty?
        redirect_to new_service_order_path
      else
        redirect_to new_service_order_path(master_id: params[:master_id])
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:startdate, :service_id, :master_id, :user_id, params[:master_id])
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/orders/index.html.erb
<% provide(:title, "Мои заказы") %>
<div class="featurette-divider col-xl-6 col-md-9 col-sm-12 mx-auto">
  <%= link_to 'Все', orders_path, class: "btn btn-dark mr-2" %>
  <% Order::STATUSES.values.each do |status| %>
    <%= link_to status.capitalize, orders_path(status: Order::STATUSES.key(status).to_s), class: "btn btn-dark mx-2" %>
  <% end %>
  <table class="table table-hover caption-top">
    <caption>Мои заказы (<%= @orders.count %>)</caption>
    <%= @status %>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Заголовок</th>
        <th scope="col">Стоимость</th>
        <th scope="col">Статус</th>
        <th scope="col">Дата</th>
        <% if current_user.master? %>
          <th scope="col">Клиент</th>
        <% else %>
          <th scope="col">Мастер</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @orders.each.with_index do |order, i| i+=1 %>
        <tr>
          <th scope="row"><%= link_to order.id, order_path(order.id) %></td></th>
          <td><%= link_to order.service.title, service_path(order.service.id) %></td>
          <td><%= number_to_currency(order.service.price) %></td>
          <td> <%= Order::STATUSES.select {|key, value| key == order.status.to_sym }.values.first.try(:capitalize) %></td>
          <td><%= l order.startdate, format: '%A, %-d %B' %></td>
          <td>
            <p>
              <% if current_user.master? %>
                <%= get_image(order.user.id)%>
                <%= order.user.name.capitalize %>
              <% else %>
                <%= get_image(order.master.id)%>
                <%= link_to order.master.name.capitalize, master_path(order.master.id) %>
              <% end %>
            </p>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<% provide(:title, "Новый заказ") %>
<%= form_with model: [@service, @service.orders.build ] do |form| %>
<div class="accordion featurette-divider w-75 mx-auto" id="menu">
  <% if flash[:danger].present? %>
    <% flash.each do |name, messages| %>
      <% messages.each do |message| %>
        <div class="bg-danger" style="--bs-bg-opacity: .5;"><%= message %></div>
      <% end %>
    <% end %>
  <% end %>
  <!-- item-1 -->
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#item-1">
        1. Выберите мастера для услуги "<%= @service.title %>"
      </button>
    </h2>
    <!-- класс show делает пункт открытым -->
    <div id="item-1" class="accordion-collapse collapse" data-bs-parent="#menu">
      <div class="accordion-body">
        <div class="row">
          <% @masters.each do |master|%>

            <div class="col-xl-2 col-md-4 col-sm-6">

                <div class="card text-center my-2">
                  <div class="text-end">
                    <%= link_to master_path(master.id) do %>
                    <i class="bi bi-info-circle text-dark m-1"></i>
                    <% end %>
                  </div>

                  <%= get_image(master.id, 90)%>
                  <span><%= master.name %></span>
                  <p>
                    <% master.fill_stars.times do %>
                      <i class="bi bi-star-fill"></i>
                    <% end %>
                    <% master.blank_stars.times do %>
                      <i class="bi bi-star"></i>
                    <% end %>
                    <br>
                    <% if params[:master_id].to_i == master.id %>
                      <i class="bi bi-check2 text-success"></i>
                    <% else %>
                      <%= link_to 'Выбрать', new_service_order_path(:master_id=>master.id), id: master.id %>
                    <% end %>
                  </p>
                </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- item-2 -->
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#item-2">
        2. Выберите дату
        <%= hidden_field_tag :master_id, params[:master_id] %>
      </button>
    </h2>
    <div id="item-2" class="accordion-collapse collapse" data-bs-parent="#menu">
      <div class="accordion-body">
            <%= form.date_field :startdate, id: "baseDate", placeholder: "Выберите время" %>

            <br>
            <%= form.submit 'Оформить заказ', class: "m-3 btn btn-outline-dark" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- partial -->

<script src='https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js'></script>
<script>
flatpickr('#baseDate', {
"minDate": new Date().fp_incr(1),
disable: <%= raw @disable_date %>,
dateFormat: "Y-m-d",
});
</script>

<!--Import vanilla wizard here-->
<script src="https://cdn.jsdelivr.net/npm/vanilla-wizard@0.0.5" >
</script>

<!--Initializing a wizard with no configuration -->
<script>
    new Wizard("#basicwizard",{
        progress: true
    });
</script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.css">

  <!--  Flatpickr  -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.js"></script>

<%= stylesheet_link_tag "flatpickr", "data-turbo-track": "reload" %>

app/views/orders/show.html.erb
<% provide(:title, "Заказ ##{@order.id}") %>
<div class="row featurette-divider">
  <div class=" col-lg-2 col-md-9 mx-3">
    <span class="fw-bold fs-4"> Заказ #<%= @order.id %></span>
    <br>
    <div class="my-2">
      <span class="fw-bold mx-auto">Наименование: </span>
      <%= link_to @order.service.title, service_path(@order.service_id) %>
    </div>

    <div class="my-2">
      <span class="fw-bold mx-auto my-3">Цена: </span><%= number_to_currency(@order.service.price) %>
    </div>

    <div class="my-2">
      <span class="fw-bold mx-auto my-3">Статус: </span><%= Order::STATUSES.select {|key, value| key == @order.status.to_sym }.values.first.try(:capitalize) %>
    </div>

    <div class="my-2">
      <span class="fw-bold mx-auto my-3">Дата: </span><%= l @order.startdate, format: '%A, %-d %B' %>
    </div>
    <p>
      <% if current_user.master? %>
        <%= get_image(@order.user.id)%>
        <%= @order.user.name.capitalize %>
      <% else %>
        <%= get_image(@order.master.id) %>
        <%= link_to @order.master.name.capitalize, master_path(@order.master.id) %>
      <% end %>
    </p>

    <% if @order.draft? && current_user.client? %>
      <%= button_to 'Отменить заказ', update_status_order_path(status: :cancel), method: :patch, class: "btn btn-sm btn-outline-dark my-sm-1" %>
    <% end %>

  </div>
  <div class="col-lg-5 col-md-9">
    <% if @order.review.present? %>
      <%= render @order.review %>
    <% end %>

    <% if @order.complete? && @order.review.nil? %>
      <h4 class="my-1">Оставить отзыв:</h4>
      <%= render 'reviews/form' %>
    <% end %>

  </div>
</div>