config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/profile'
  resources :services do
    resources :orders, only: %i[create new]
  end

  resources :orders, only: %i[index show] do
    resources :reviews
    member do
      patch :update_status
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  devise_for :users
  resources :users
  get 'gallery', to: 'static_pages#gallery'
  get 'profile', to: 'users#profile'
  get 'masters', to: 'masters#index'
  resources :masters, only: %i[index show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | LavenderSpa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'lavanda.png' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>

  <body>

    <header>

      <nav class="navbar navbar-inverse navbar-expand-md navbar-light fixed-top bg-white border-bottom">
        <div class="container-fluid">
            <%= image_tag("label.png", size: "160x70", class: "px-2") %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0 ">
              <li class="nav-item">
                <%= link_to 'Главная', root_path, class: "nav-link mx-3 text-dark" %></a>
              </li>
              <li class="nav-item">
                <a href="/#about" class="nav-link mx-3 text-dark">О нас</a>
              </li>
              <li class="nav-item">
                <a href="#contact" class="nav-link mx-3 text-dark">Контакты</a>
              </li>
              <li class="nav-item">
                <%= link_to 'Услуги', services_path, class: "nav-link mx-3 text-dark" %></a>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Заказы', orders_path, class: "nav-link mx-3 text-dark" %></a>
                </li>
              <% end %>
            </ul>
            <% if user_signed_in? %>

              <div class="dropdown mx-2 px-5">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= get_image(current_user.id)%>
                </a>
                <ul class="dropdown-menu text-small mx-3" aria-labelledby="dropdownUser1">
                  <li><%= link_to "Профиль", profile_path, class: "mx-4" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <%= button_to "Выйти", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "btn btn-dark mx-3" %>
                  </li>
                </ul>
              </div>

            <% else %>
              <%= link_to 'Войти', new_user_session_path, class: "text-dark mx-3" %>
              <br class="d-md-none">
              <%= link_to 'Зарегистрироваться', new_user_registration_path, class: "btn btn-outline-dark my-sm-3" %>
            <% end %>

          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>

    <!-- FOOTER -->
    <footer class="container">
      <hr class="my-5">
      <div class="row  text-center">
        <div class="col-sm-12 col-md-4">
          <p class="fw-bold" id="contact">Местоположение</p>
          <p>Lavender Spa </p>
          <p>26700 Beck Rd.</p>
          <p>Novi, MI 48374</p>
        </div>
        <div class="col-sm-12 col-md-4">
          <p class="fw-bold" id="contact">Информация</p>
          <p>Телефон: +375298257319</p>
          <p>info@lavenderspa.com</p>
        </div>
        <div class="col-sm-12 col-md-4">
          <p class="fw-bold">Время работы</p>
          <p>Понедельник: 10:00 - 6:00</p>
          <p>Вторник-Четверг: 9:00 - 9:00</p>
          <p>Пятница: 8:30 - 5:00</p>
          <p>Суббота: 10:30 - 5:00</p>
        </div>
      </div>
      <p>&copy; 2022–2023 LavenderSpa, Inc. &middot; <a href="#">Политика конфиденциальности</a> &middot; <a href="#">Правила</a></p>
      <!-- /END THE FEATURETTES -->

    </footer>
  </body>
</html>